sudo: required
language: python
services:
- docker
install:
- echo "install nothing!"
script:
- echo "no tests!"
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
env:
  global:
  - REPO=pdaugavietis/base-centos
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: osfUlEuC5cDqLqP1leCHV89rP/6kLtYLsT6M5me/B/2fPqUCc4wCyH1IR4oPDRQGbZrkhzFS+WbeZG6XXRyHh9cPdstGssFhRArj6ab7sVNTFVsv+WnwBHpZgq6ONm7MTHhnWMjCf7ojPxrO/mlJBbttPGzVccK/W29YjI5ToaklpBY+yAOdAo5wM2I+KgQO+pJP60q0dAgmkpXQIx5vT18I0MUrkVNVxFwZQki7uO2E5cjUJGgAHbO5egeNw+AMRIJ0b0sAr3WUQ6rhHisIY5Qqnu1m7H0zL47U59ONQsgAFEwWPZ0BQXG9xur5i3Q0rmxs6MiWhTWOFehw3QTXm+g/z97rzDdZfI8mjEI7q70Y4AO4eVA7gLqsiN2QKacDGA7N1AJYps/CfXXG7KoD6IcsGKYXn+LEGx31BEJHrvtg32qiVyRnx+fpjbN9N9ZJJZV5rAX4aq2XKNkqoGanYHMLPcKx0AU93XRV2XebHqpmqBNmnn8P3YdeLFbP1dIoOfBUlMUKGojqJgnTJAG3MgH7lxD+LEMyAXX1dQBfqhhS2C/viaIgcLcPG4EbuyYmuBUtsxCCHkm/MtMgBhAfpcs/RV/97DzHOHA+MLXTsIDINTksa8NAg3dM2R0GIyqMqJxqItbKD4fZYHfs/oHT//46hH2IlSy2EdGfBrsvw3A=
  - secure: mqvm+MIdz+WxCbSxp0XQ735yaeWPUCqtzT6ljnB3X5JT1I4eHr+7Q1WOfCyph47WRllgbYCy+IXi00Y7y6YjJlJUHYiBUJgwBhiO8lCrVW0Q+12g4FWuv9NYLHphEJqRkVZdQztiFatK92raYmiHkwseHXOby+Nv7hLAsKn10fIIdr/dVm6HAG12f4ILwggnPx+IZDnmRJDv4R7RxOajBJiplPcBzJqUXvzFgFeKR73n0HNROsRuerhQJY3WlWzVf78X7Qwd66I3AZQGoHm4j7XJa9xdSmLF5b7SIrSdwofzyB64EMfmdzoALTKlVNUQkVYkRwDy6v2dpEo+favJ+PjoX5NJsCRC0aKEAbEJf3E5Pnp++Dj6JEhVNzoCVWysjjSRKjUNo0tzsr+q0wrA3VV5zE3J7E3GkH7LC9IzmUaf0vHh176Vwr/tit27wx7w9mfiUU2lF8hZwMhQ+FqpGi4waJ0QUFfj7q5A9l738hhEdUElkc+H/GK/J4fJt7jLIUWJ+It9hQ3udui3xY1mhZ6sOeMs+dBt7Y+uwy3eJ8v/ufHoBbre2d9hRXHbx+1gKL/T+y04SHq+RKnW709tLluAonrlOJfQfNgMHUgkyejgGg8xfwChIGzsP3W0FLz4gc6IH8yMeZNYup0IREMOXjJ+is3+EOS7i84BWs7oq1o=
  - secure: mQaHI4I4kGzZTpjPvvQidajyck/DpMsyfuUs2oQbWR3LXU59XzwlxMDa1ASONR3ArFnto8gz7dNI1O88Zdg8LJpJS4nuZ55npfe9Q0zM450VUuLDK+pTfeX9gouQoLxh+cpjuQSrc1mMZky9YTWojThrn78E29c5ek3bGweucgRdND7XHy/XvikL5dLys6WOsYySdHYGbUR/zF7ijMkuLw0jKYLeUxxrA7yY40rMnsRVuiIjd9NoS3R0QScR/nG/zZyVzUZ/5LbpZ9ErIxDqZy3cJqy6SesL6I0ZIzPcoL8ZNObdk2xGYUj7YcNARnzC9/Bl47L5U2yNN0ue/NcagmBueEUR1zsHpPAUfLIV+EeTqFTBv4IRtZz6G4BQWNfCPXRjqqfhoBR+uyVrm+dwjb5jMAQdAmCkebPbKpYeYLSGp5gymo4r0Ca/2WNEqz3TBLrHdhhn2brcwPdqCWfA/Zv3O75B0xn35IAJiF5yq/CT0pNYsM5fzqpUqRnsYJSuWpva8kHqJvj3PAi2j0U8PSonSF4EhxhvxHgJTsk8sgPrXTM6UNUWAVnpdVLOGvVi9cl/yzL7hAXYjuA5pj2L/Mcr0olG0jFcVMvAV79b4naKXDE8zm5f/rsRDdGvA+xQfseme/KIJ4U1KiEH6tlJgXD676w005XR+emQ27gixYo=

after_success:
- export REPO=pdaugavietis/base-centos
- export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
- export TAG=`if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $BRANCH; fi`
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, REPO=$REPO, PR=$PR, BRANCH=$BRANCH, TAG=$TAG"
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker images
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
